name: Check Removed Interfaces, Types, and Export Declarations

on:
  pull_request:
    branches:
      - '*'

jobs:
  check-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Checkout the current branch
          path: current_branch  # Store the contents in a directory named 'current_branch'

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          sparse-checkout: | # checkout only index.d.ts file
            index.d.ts 
          sparse-checkout-cone-mode: false
          ref: main  # Checkout the main branch
          path: main_branch  # Store the contents in a directory named 'main_branch'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./current_branch  # Switch working directory to 'current_branch'
        run: npm install
      - name: List files
        run: ls -la

      - name: Compile TypeScript code
        working-directory: ./current_branch  # Switch working directory to 'current_branch'
        run: npx tsc check-modules.ts

      - name: Run TypeScript check
        run: |
          node current_branch/check-modules.js --current-file-path current_branch/index.d.ts --legacy-file-path main_branch/index.d.ts
