name: Check Removed Interfaces, Types, and Export Declarations

on:
  pull_request:
    branches:
      - '*'

jobs:
  check-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main  # Checkout the main branch
          path: main  # Store the contents in a directory named 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript code
        run: npx tsc check-typescript.ts

      - name: Run TypeScript check
        run: |
          node check-typescript.js main/index.d.ts index.d.ts
